import {
  NextResponse,
  type NextFetchEvent,
  type NextRequest,
} from "next/server";
import { trackAICrawlerRequest } from "@datafast/ai-crawl";

// Server-side bot traffic tracking for DataFast. This is separate from the
// browser tracking script in app/layout.tsx: AI crawlers request raw HTML and
// skip frontend JavaScript, so they never show up in the client-side script.
//
// `event` is passed so the package can use Vercel's waitUntil internally —
// the DataFast call is scheduled in the background. Never await this; call it
// and return the response immediately.
export function proxy(request: NextRequest, event: NextFetchEvent) {
  trackAICrawlerRequest(request, event, {
    // Same public website ID as the browser script in app/layout.tsx.
    websiteId: "dfid_swcipYZ3Rc55HGLL1A7A4",
    // Optional until a Bot traffic token is created in the DataFast dashboard.
    // Undefined here simply means the request is sent unauthenticated, which
    // DataFast accepts unless "Reject unauthenticated requests" is enabled.
    authToken: process.env.DATAFAST_BOT_TOKEN,
  });

  return NextResponse.next();
}

export const config = {
  // Skips API routes and framework internals. Crawler-facing files are
  // deliberately left in: /robots.txt and /sitemap.xml (generated by
  // app/robots.ts and app/sitemap.ts) are usually the first things a crawler
  // requests, and seeing those hits is the point.
  matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
};
