/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  author: AuthorReference;
  categories: Array<{
    _key: string;
  } & CategoryReference>;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedDate: string;
  updatedDate: string;
  body: BlogBody;
  seo?: Seo;
  sourceId?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type BlogBody = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & ComparisonTable>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ComparisonTable = {
  _type: "comparisonTable";
  headers: Array<string>;
  rows: Array<{
    _key: string;
  } & TableRow>;
};

export type TableRow = {
  _type: "tableRow";
  cells: Array<string>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sourceId?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: string;
  sourceId?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = AuthorReference | CategoryReference | SanityImageAssetReference | BlogPost | Seo | BlogBody | SanityImageCrop | SanityImageHotspot | Slug | ComparisonTable | TableRow | Category | Author | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)]  | order(publishedDate desc, _id asc){      _id,  title,  "slug": slug.current,  description,  publishedDate,  updatedDate,  "author": author->{name, role},  "categories": categories[]->{title, "slug": slug.current},  "mainImage": mainImage{  asset->{    _id,    url,    metadata{      lqip,      dimensions{width, height}    }  },  alt,  crop,  hotspot},  "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description, description, ""),    "noIndex": seo.noIndex == true,    "image": seo.image{  asset->{    _id,    url,    metadata{      lqip,      dimensions{width, height}    }  },  alt,  crop,  hotspot}  }  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  publishedDate: string;
  updatedDate: string;
  author: {
    name: string;
    role: string | null;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  seo: {
    title: string;
    description: string;
    noIndex: boolean | false;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  description,  publishedDate,  updatedDate,  "author": author->{name, role},  "categories": categories[]->{title, "slug": slug.current},  "mainImage": mainImage{  asset->{    _id,    url,    metadata{      lqip,      dimensions{width, height}    }  },  alt,  crop,  hotspot},  "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description, description, ""),    "noIndex": seo.noIndex == true,    "image": seo.image{  asset->{    _id,    url,    metadata{      lqip,      dimensions{width, height}    }  },  alt,  crop,  hotspot}  },    body[]{      ...,      _type == "comparisonTable" => {        _key,        _type,        headers,        rows[]{_key, _type, cells}      }    }  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string;
  publishedDate: string;
  updatedDate: string;
  author: {
    name: string;
    role: string | null;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  seo: {
    title: string;
    description: string;
    noIndex: boolean | false;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  };
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "comparisonTable";
    headers: Array<string>;
    rows: Array<{
      _key: string;
      _type: "tableRow";
      cells: Array<string>;
    }>;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: BLOG_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)]{"slug": slug.current}
export type BLOG_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_SITEMAP_QUERY
// Query: *[_type == "blogPost" && defined(slug.current) && seo.noIndex != true]  | order(publishedDate desc){    "slug": slug.current,    "updatedDate": coalesce(updatedDate, _updatedAt)  }
export type BLOG_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  updatedDate: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"blogPost\" && defined(slug.current)]\n  | order(publishedDate desc, _id asc){\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  description,\n  publishedDate,\n  updatedDate,\n  \"author\": author->{name, role},\n  \"categories\": categories[]->{title, \"slug\": slug.current},\n  \"mainImage\": mainImage{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{width, height}\n    }\n  },\n  alt,\n  crop,\n  hotspot\n},\n  \"seo\": {\n    \"title\": coalesce(seo.title, title, \"\"),\n    \"description\": coalesce(seo.description, description, \"\"),\n    \"noIndex\": seo.noIndex == true,\n    \"image\": seo.image{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{width, height}\n    }\n  },\n  alt,\n  crop,\n  hotspot\n}\n  }\n\n  }\n": BLOG_POSTS_QUERY_RESULT;
    "\n  *[_type == \"blogPost\" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  description,\n  publishedDate,\n  updatedDate,\n  \"author\": author->{name, role},\n  \"categories\": categories[]->{title, \"slug\": slug.current},\n  \"mainImage\": mainImage{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{width, height}\n    }\n  },\n  alt,\n  crop,\n  hotspot\n},\n  \"seo\": {\n    \"title\": coalesce(seo.title, title, \"\"),\n    \"description\": coalesce(seo.description, description, \"\"),\n    \"noIndex\": seo.noIndex == true,\n    \"image\": seo.image{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{width, height}\n    }\n  },\n  alt,\n  crop,\n  hotspot\n}\n  }\n,\n    body[]{\n      ...,\n      _type == \"comparisonTable\" => {\n        _key,\n        _type,\n        headers,\n        rows[]{_key, _type, cells}\n      }\n    }\n  }\n": BLOG_POST_QUERY_RESULT;
    "\n  *[_type == \"blogPost\" && defined(slug.current)]{\"slug\": slug.current}\n": BLOG_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"blogPost\" && defined(slug.current) && seo.noIndex != true]\n  | order(publishedDate desc){\n    \"slug\": slug.current,\n    \"updatedDate\": coalesce(updatedDate, _updatedAt)\n  }\n": BLOG_SITEMAP_QUERY_RESULT;
  }
}

